# Cargo configuration for Unikraft x86_64 build
# PIE-compatible for elfloader
# Note: We embed the trampoline as binary blob, no linking needed

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-Ttls_linker.ld"]


